[build]
  publish = "public"
  command = ""

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# Proste API aliasy
[[redirects]]
  from = "/api/messages"
  to = "/.netlify/functions/messages"
  status = 200
  force = true

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200
  force = true

# Brak cache po stronie przeglądarki
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"
