[build]
  publish = "."
  node_bundler = "esbuild"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# ===== Alias API =====
# Chat messages
[[redirects]]
  from = "/api/messages"
  to   = "/.netlify/functions/messages"
  status = 200

# Upload (attachments)
[[redirects]]
  from = "/api/upload"
  to   = "/.netlify/functions/upload"
  status = 200
