[build]
  publish = "."  # serwuj statyczne pliki z głównego katalogu

[[redirects]]
  from = "/api/hello"
  to   = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/api/messages"
  to   = "/.netlify/functions/messages"
  status = 200

[[redirects]]
  from = "/api/upload"
  to   = "/.netlify/functions/upload"
  status = 200
