[build]
  publish   = "."
  functions = "netlify/functions"

# Włącza Netlify Blobs w projekcie
[[plugins]]
  package = "@netlify/blobs"

# Na produkcji Netlify wstrzyknie SITE_ID automatycznie.
# Lokalnie można ustawić env NETLIFY_SITE_ID jeśli używasz netlify-cli.
[blobs]
  site_id = ""
