# netlify.toml
[functions]
  node_bundler = "esbuild"

# API proxy
[[redirects]]
  from = "/api/messages"
  to   = "/.netlify/functions/messages"
  status = 200

# (opcjonalnie — jeżeli kiedyś dodasz upload)
[[redirects]]
  from = "/api/upload"
  to   = "/.netlify/functions/upload"
  status = 200
