[build]
  publish = "."
  node_bundler = "esbuild"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Alias HTTP -> Function
[[redirects]]
  from = "/api/blobs-health"
  to   = "/.netlify/functions/blobs-health"
  status = 200
