// Export Netlify TOML content as a string to avoid JS parse errors (consider renaming this file to `netlify.toml`)
module.exports = `[build]
  publish = "."
  node_bundler = "esbuild"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# --- API aliasy ---
# contracts
[[redirects]]
  from = "/api/contracts"
  to   = "/.netlify/functions/contracts"
  status = 200
[[redirects]]
  from = "/api/contracts/*"
  to   = "/.netlify/functions/contracts/:splat"
  status = 200

# docs
[[redirects]]
  from = "/api/docs"
  to   = "/.netlify/functions/docs"
  status = 200
[[redirects]]
  from = "/api/docs/*"
  to   = "/.netlify/functions/docs/:splat"
  status = 200

# tasks
[[redirects]]
  from = "/api/tasks"
  to   = "/.netlify/functions/tasks"
  status = 200
[[redirects]]
  from = "/api/tasks/*"
  to   = "/.netlify/functions/tasks/:splat"
  status = 200

# messages (chat)
[[redirects]]
  from = "/api/messages"
  to   = "/.netlify/functions/messages"
  status = 200

# upload (chat attachments)
[[redirects]]
  from = "/api/upload"
  to   = "/.netlify/functions/upload"
  status = 200
`;
