
[[redirects]]
  from = "/api/contracts"
  to   = "/.netlify/functions/contracts"
  status = 200

# Obsługa ścieżek typu /api/contracts/ID → ta sama funkcja
[[redirects]]
  from = "/api/contracts/*"
  to   = "/.netlify/functions/contracts/:splat"
  status = 200
