# === Build ===
[build]
  publish = "."
  node_bundler = "esbuild"

# === Functions ===
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# === API aliasy (rewrites do Functions) ===

# contracts
[[redirects]]
  from = "/api/contracts"
  to   = "/.netlify/functions/contracts"
  status = 200
[[redirects]]
  from = "/api/contracts/*"
  to   = "/.netlify/functions/contracts/:splat"
  status = 200

# docs (upload/list/pobieranie plików)
[[redirects]]
  from = "/api/docs"
  to   = "/.netlify/functions/docs"
  status = 200
[[redirects]]
  from = "/api/docs/*"
  to   = "/.netlify/functions/docs/:splat"
  status = 200

# tasks
[[redirects]]
  from = "/api/tasks"
  to   = "/.netlify/functions/tasks"
  status = 200
[[redirects]]
  from = "/api/tasks/*"
  to   = "/.netlify/functions/tasks/:splat"
  status = 200

# chat: messages
[[redirects]]
  from = "/api/messages"
  to   = "/.netlify/functions/messages"
  status = 200
[[redirects]]
  from = "/api/messages/*"
  to   = "/.netlify/functions/messages/:splat"
  status = 200

# chat: upload załączników
[[redirects]]
  from = "/api/upload"
  to   = "/.netlify/functions/upload"
  status = 200
[[redirects]]
  from = "/api/upload/*"
  to   = "/.netlify/functions/upload/:splat"
  status = 200

# (opcjonalnie) ping/hello — jeśli masz hello.js
[[redirects]]
  from = "/api/hello"
  to   = "/.netlify/functions/hello"
  status = 200

# (opcjonalnie) wyłączieserwerowe cachowanie dla HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# (opcjonalnie) podstawowe CORS dla statycznych (funkcje mają swoje nagłówki)
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*
