
[build]
  publish = "."
  node_bundler = "esbuild"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# --- API aliasy ---

# contracts
[[redirects]]
  from = "/api/contracts"
  to   = "/.netlify/functions/contracts"
  status = 200

[[redirects]]
  from = "/api/contracts/*"
  to   = "/.netlify/functions/contracts/:splat"
  status = 200

# docs
[[redirects]]
  from = "/api/docs"
  to   = "/.netlify/functions/docs"
  status = 200

[[redirects]]
  from = "/api/docs/*"
  to   = "/.netlify/functions/docs/:splat"
  status = 200

# tasks
[[redirects]]
  from = "/api/tasks"
  to   = "/.netlify/functions/tasks"
  status = 200

[[redirects]]
  from = "/api/tasks/*"
  to   = "/.netlify/functions/tasks/:splat"
  status = 200

# messages (chat)
[[redirects]]
  from = "/api/messages"
  to   = "/.netlify/functions/messages"
  status = 200

# upload (chat attachments)
[[redirects]]
  from = "/api/upload"
  to   = "/.netlify/functions/upload"
  status = 200

# --- Nagłówki ---

# brak cachowania HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# CORS dla wszystkich zasobów (statycznych)
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
