[build]
  publish = "."
  node_bundler = "esbuild"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# === REST aliasy dla funkcji ===
# CHAT
[[redirects]]
  from = "/api/messages"
  to   = "/.netlify/functions/messages"
  status = 200
[[redirects]]
  from = "/api/messages/*"
  to   = "/.netlify/functions/messages/:splat"
  status = 200
[[redirects]]
  from = "/api/upload"
  to   = "/.netlify/functions/upload"
  status = 200

# DOCS
[[redirects]]
  from = "/api/docs"
  to   = "/.netlify/functions/docs"
  status = 200
[[redirects]]
  from = "/api/docs/*"
  to   = "/.netlify/functions/docs/:splat"
  status = 200

# CONTRACTS
[[redirects]]
  from = "/api/contracts"
  to   = "/.netlify/functions/contracts"
  status = 200
[[redirects]]
  from = "/api/contracts/*"
  to   = "/.netlify/functions/contracts/:splat"
  status = 200

# TASKS (jeśli używasz)
[[redirects]]
  from = "/api/tasks"
  to   = "/.netlify/functions/tasks"
  status = 200
[[redirects]]
  from = "/api/tasks/*"
  to   = "/.netlify/functions/tasks/:splat"
  status = 200
